export const allUsers = [
  {
    name: "Alex Carter",
    location: "Brooklyn, NY",
    bio: "Chasing sunsets and good vibes 📸",
    numPictures: 4,
    interests: ["Hiking", "Coffee", "Travel", "Live Music"],
    traits: [
      { name: "Adventurous", description: "Always up for a spontaneous trip" },
      {
        name: "Creative",
        description: "Loves capturing moments through a lens",
      },
    ],
    favorites: [
      { category: "book", favorite: "The Alchemist" },
      { category: "song", favorite: "Bohemian Rhapsody" },
    ],
    lookingFor: "Someone who loves exploring new places and sharing stories",
    conversationStarters: [
      "What's the best hike you've ever done?",
      "Got a favorite coffee spot?",
      "What's the story behind your favorite photo?",
    ],
    favoriteLocations: ["Blue Bottle Coffee", "Prospect Park"],
    mutualFriends: 0,
    timeMet: "10:45 AM",
    distance: 42,
    timeTogether: 25,
  },
  {
    name: "Sofia Mendes",
    location: "Austin, TX",
    bio: "Music enthusiast and taco connoisseur 🌮🎶",
    interests: ["Live Music", "Cooking", "Yoga"],
    favorites: [
      { category: "food", favorite: "Breakfast tacos" },
      { category: "song", favorite: "Texas Sun" },
      { category: "movie", favorite: "Before Sunrise" },
    ],
    conversationStarters: [
      "What's the best concert you've been to?",
      "Got a go-to taco recipe?",
    ],
    mutualFriends: 1,
    timeMet: "2:30 PM",
    distance: 78,
    timeTogether: 12,
  },
  {
    name: "Liam Zhang",
    location: "San Francisco, CA",
    bio: "Tech geek by day, stargazer by night ✨",
    numPictures: 5,
    interests: ["Astronomy", "Board Games", "Sci-Fi Movies", "Hiking"],
    traits: [
      { name: "Curious", description: "Always learning something new" },
      { name: "Introverted", description: "Enjoys quiet evenings with a book" },
      { name: "Witty", description: "Loves a good pun" },
    ],
    lookingFor: "A fellow nerd to geek out with",
    favoriteLocations: ["Golden Gate Park", "City Lights Bookstore"],
    mutualFriends: 0,
    timeMet: "7:20 PM",
    distance: 19,
    timeTogether: 48,
  },
  {
    name: "Maya Patel",
    location: "Chicago, IL",
    bio: "Art lover and city explorer 🎨🏙️",
    numPictures: 3,
    interests: ["Painting", "Architecture", "Food Tours"],
    conversationStarters: [
      "What's the coolest museum you've visited?",
      "Favorite Chicago dish?",
    ],
    favoriteLocations: ["Art Institute of Chicago", "Millennium Park"],
    mutualFriends: 0,
    timeMet: "11:10 AM",
    distance: 65,
    timeTogether: 33,
  },
  {
    name: "Ethan Brooks",
    location: "Seattle, WA",
    bio: "Craft beer enthusiast and dog dad 🐶🍺",
    numPictures: 12,
    interests: ["Brewing", "Hiking", "Dog Training", "Camping"],
    favorites: [
      { category: "drink", favorite: "IPA" },
      { category: "book", favorite: "Dune" },
    ],
    lookingFor: "Someone to share a pint and a trail with",
    favoriteLocations: ["Fremont Brewing", "Discovery Park"],
    mutualFriends: 5,
    timeMet: "3:50 PM",
    distance: 27,
    timeTogether: 55,
  },
  {
    name: "Luna Garcia",
    location: "Miami, FL",
    bio: "Dancing through life with a Latin beat 💃",
    traits: [
      { name: "Energetic", description: "Always moving to the rhythm" },
      { name: "Friendly", description: "Loves meeting new people" },
    ],
    conversationStarters: [
      "What's your go-to dance move?",
      "Favorite spot for a night out in Miami?",
    ],
    mutualFriends: 0,
    timeMet: "8:25 PM",
    distance: 93,
    timeTogether: 40,
  },
  {
    name: "Noah Kim",
    location: "Portland, OR",
    bio: "Food trucks and forest trails 🌲🍔",
    numPictures: 1,
    interests: ["Camping", "Street Food", "Photography"],
    favorites: [
      { category: "food", favorite: "Kimchi fries" },
      { category: "song", favorite: "Harvest Moon" },
      { category: "book", favorite: "Wild" },
    ],
    favoriteLocations: ["Forest Park", "Pine State Biscuits"],
    mutualFriends: 3,
    timeMet: "9:00 AM",
    distance: 51,
    timeTogether: 18,
  },
  {
    name: "Ava Nguyen",
    location: "Boston, MA",
    bio: "Bookworm and history buff 📚🏛️",
    traits: [{ name: "Thoughtful", description: "Loves deep conversations" }],
    lookingFor: "Someone to explore old bookstores with",
    conversationStarters: [
      "What's a book you couldn't put down?",
      "Favorite historical site in Boston?",
    ],
    favoriteLocations: ["Boston Public Library", "Freedom Trail"],
    mutualFriends: 0,
    timeMet: "1:15 PM",
    distance: 34,
    timeTogether: 29,
  },
  {
    name: "Omar Saleh",
    location: "Denver, CO",
    bio: "Mountain climber and coffee addict ☕🏔️",
    numPictures: 5,
    interests: [
      "Rock Climbing",
      "Skiing",
      "Coffee Roasting",
      "Camping",
      "Photography",
      "Mountain Biking",
      "Craft Beer",
    ],
    favorites: [{ category: "drink", favorite: "Cortado" }],
    lookingFor: "An adventure buddy for the trails",
    favoriteLocations: ["Red Rocks Park", "Little Owl Coffee"],
    mutualFriends: 0,
    timeMet: "6:40 AM",
    distance: 82,
    timeTogether: 44,
  },
  {
    name: "Zoe Harper",
    location: "Los Angeles, CA",
    bio: "Dreamer, writer, and beach bum 🌊✍️",
    numPictures: 12,
    interests: [
      "Writing",
      "Surfing",
      "Poetry",
      "Yoga",
      "Photography",
      "Meditation",
    ],
    traits: [
      { name: "Creative", description: "Always working on a new story" },
      { name: "Relaxed", description: "Loves chilling by the ocean" },
    ],
    conversationStarters: [
      "What's the last thing you wrote?",
      "Best beach in LA?",
    ],
    favoriteLocations: ["Venice Beach", "The Last Bookstore"],
    mutualFriends: 2,
    timeMet: "4:05 PM",
    distance: 15,
    timeTogether: 37,
  },
];

export function getRandomUser() {
  return allUsers[Math.floor(Math.random() * allUsers.length)];
}

export function getRandomUsers(count: number) {
  return [...allUsers].sort(() => Math.random() - 0.5).slice(0, count);
}
